import React from 'react';
import { generateClinicalReport } from '../services/reportGenerator';
import { HealthySkinReport } from './HealthySkinReport';
import { DiseaseReport } from './DiseaseReport';
import { ProbabilityList } from './ProbabilityList';
import { useLanguage } from '../context/LanguageContext';
import { AlertCircle, Download, ShieldCheck, User, Calendar, Tag, Cpu } from 'lucide-react';

interface ClinicalReportProps {
  predictionData: any;
  scannedImageUrl: string;
  onDownloadReport?: () => void;
}

export const ClinicalReport: React.FC<ClinicalReportProps> = ({
  predictionData,
  scannedImageUrl,
  onDownloadReport
}) => {
  const { currentLang, t } = useLanguage();
  const reportPayload = generateClinicalReport(predictionData, scannedImageUrl);

  const isTa = currentLang === 'ta';
  const isHi = currentLang === 'hi';

  // Validation Failure UI
  if (!reportPayload.isValid) {
    return (
      <div className="bg-rose-50 border-2 border-rose-300 rounded-2xl p-8 max-w-3xl mx-auto my-8 text-center shadow-md">
        <AlertCircle className="w-12 h-12 text-rose-600 mx-auto mb-4" />
        <h2 className="text-xl font-black text-rose-950 uppercase mb-2">
          {isTa ? 'பரிசோதனை சரிபார்ப்பு பிழை' : isHi ? 'स्क्रीनिंग सत्यापन त्रुटि' : 'Screening Verification Error'}
        </h2>
        <p className="text-rose-800 font-semibold text-base mb-6">
          {reportPayload.errorMessage || (isTa ? 'இந்தப் படத்திற்கான அறிக்கையை உருவாக்க முடியவில்லை. தெளிவான படத்தைப் பயன்படுத்தவும்.' : isHi ? 'इस छवि के लिए रिपोर्ट तैयार करने में असमर्थ। कृपया एक स्पष्ट छवि का उपयोग करें।' : 'Unable to generate a reliable screening report for this image. Please rescan using a clear, well-lit image.')}
        </p>
      </div>
    );
  }

  const {
    patientName,
    scanId,
    scanDateTime,
    modelVersion,
    confidencePct,
    isNormalSkin,
    diseaseResult,
    topProbabilities
  } = reportPayload;

  const handlePrintDownload = () => {
    if (onDownloadReport) {
      onDownloadReport();
      return;
    }
    window.print();
  };

  const sysTitle = isTa ? 'டெர்மாவிஷன் AI மருத்துவ அமைப்பு' : isHi ? 'डर्माविज़न एआई क्लिनिकल सिस्टम' : 'DermaVision AI Clinical System';
  const reportMainTitle = isTa ? 'தோல் பரிசோதனை மருத்துவ அறிக்கை' : isHi ? 'त्वचा स्क्रीनिंग क्लिनिकल रिपोर्ट' : 'Clinical Skin Screening Report';
  const reportSub = isTa ? 'தானியங்கி ஆழமான கற்றல் தோல் முறை மதிப்பீடு' : isHi ? 'स्वचालित दीप लर्निंग त्वचीय पैटर्न मूल्यांकन' : 'Automated Deep Learning Cutaneous Pattern Evaluation';
  const downloadBtnText = isTa ? 'அறிக்கையைப் பதிவிறக்குக' : isHi ? 'रिपोर्ट डाउनलोड करें' : 'Download Report';

  const patientLabel = isTa ? 'நோயாளி' : isHi ? 'रोगी' : 'Patient';
  const scanIdLabel = isTa ? 'ஸ்கேன் ஐடி' : isHi ? 'स्कैन आईडी' : 'Scan ID';
  const scanTimeLabel = isTa ? 'ஸ்கேன் நேரம்' : isHi ? 'स्कैन का समय' : 'Scan Time';
  const aiEngineLabel = isTa ? 'AI இன்ஜின்' : isHi ? 'एआई इंजन' : 'AI Engine';

  const disclaimerTitle = isTa ? 'முக்கியமான மருத்துவ பாதுகாப்பு மற்றும் நோக்கம் மறுப்பு' : isHi ? 'महत्वपूर्ण चिकित्सा सुरक्षा एवं नैदानिक दायरा अस्वीकरण' : 'Important Medical Safety & Clinical Scope Disclaimer';
  const disclaimerBody1 = isTa
    ? 'AI பரிசோதனை முடிவு அறிவிப்பு: இந்த ஆவணம் 153 தோல் நோய்கள் குறித்து பயிற்சி பெற்ற ஆழமான கற்றல் கணினி பார்வை அல்காரிதம்களால் உருவாக்கப்பட்ட AI-உதவி பரிசோதனை மதிப்பீடாகும்.'
    : isHi
    ? 'एआई स्क्रीनिंग परिणाम सूचना: यह दस्तावेज़ 153 त्वचा स्थिति वर्गों में प्रशिक्षित गहरे शिक्षण कंप्यूटर दृष्टि एल्गोरिदम द्वारा उत्पन्न एक एआई-सहायता प्राप्त स्क्रीनिंग मूल्यांकन का प्रतिनिधित्व करता है।'
    : 'AI Screening Result Notice: This document represents an AI-assisted screening evaluation generated by deep learning computer vision algorithms trained across 153 skin condition classes.';
  const disclaimerBody2 = isTa
    ? 'இது ஒரு உறுதிப்படுத்தப்பட்ட மருத்துவ நோயறிதல் அல்லது தகுதியான மருத்துவர் மதிப்பீட்டிற்கான மாற்று அல்ல.'
    : isHi
    ? 'यह एक पुष्टि की गई चिकित्सा निदान या योग्य चिकित्सक मूल्यांकन का विकल्प नहीं है।'
    : 'It is not a confirmed medical diagnosis or a substitute for evaluation by a qualified healthcare professional.';

  return (
    <div className="bg-white border border-slate-300 rounded-2xl shadow-xl max-w-4xl mx-auto overflow-hidden print:shadow-none print:border-none">
      {/* Clinical Report Header Banner */}
      <div className="bg-slate-900 text-white p-6 md:p-8 border-b-4 border-indigo-600 print:bg-white print:text-black print:border-b-2 print:border-black">
        <div className="flex flex-wrap justify-between items-start gap-4">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <ShieldCheck className="w-6 h-6 text-indigo-400 print:text-black" />
              <span className="text-xs font-black uppercase tracking-widest text-indigo-300 print:text-slate-600">
                {sysTitle}
              </span>
            </div>
            <h1 className="text-2xl md:text-3xl font-black tracking-tight">
              {reportMainTitle}
            </h1>
            <p className="text-xs text-slate-400 mt-1 print:text-slate-600">
              {reportSub}
            </p>
          </div>

          <button
            onClick={handlePrintDownload}
            className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-xs uppercase px-4 py-2.5 rounded-xl shadow-sm transition-all print:hidden"
          >
            <Download className="w-4 h-4" />
            <span>{downloadBtnText}</span>
          </button>
        </div>

        {/* Header Metadata Grid */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-6 pt-6 border-t border-slate-800 text-xs print:border-slate-300 print:text-black">
          <div className="flex items-center gap-2">
            <User className="w-4 h-4 text-slate-400 print:text-black shrink-0" />
            <div>
              <span className="text-slate-400 block text-[10px] uppercase font-bold print:text-slate-600">{patientLabel}</span>
              <span className="font-semibold">{patientName}</span>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <Tag className="w-4 h-4 text-slate-400 print:text-black shrink-0" />
            <div>
              <span className="text-slate-400 block text-[10px] uppercase font-bold print:text-slate-600">{scanIdLabel}</span>
              <span className="font-mono font-semibold">{scanId}</span>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <Calendar className="w-4 h-4 text-slate-400 print:text-black shrink-0" />
            <div>
              <span className="text-slate-400 block text-[10px] uppercase font-bold print:text-slate-600">{scanTimeLabel}</span>
              <span className="font-semibold">{scanDateTime}</span>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <Cpu className="w-4 h-4 text-slate-400 print:text-black shrink-0" />
            <div>
              <span className="text-slate-400 block text-[10px] uppercase font-bold print:text-slate-600">{aiEngineLabel}</span>
              <span className="font-semibold">{modelVersion}</span>
            </div>
          </div>
        </div>
      </div>

      {/* Main Clinical Report Body */}
      <div className="p-6 md:p-8 space-y-6">
        {/* Dynamic Branching: Normal / Healthy Skin vs Disease Report */}
        {isNormalSkin ? (
          <HealthySkinReport scannedImageUrl={scannedImageUrl} />
        ) : (
          diseaseResult && (
            <DiseaseReport
              diseaseResult={diseaseResult}
              confidencePct={confidencePct}
              scannedImageUrl={scannedImageUrl}
            />
          )
        )}

        {/* Top 3 Predictions Section (>= 5% Probability) */}
        <ProbabilityList probabilities={topProbabilities} />

        {/* Medical Safety & Legal Disclaimer */}
        <div className="bg-slate-50 border border-slate-200 rounded-xl p-5 text-slate-600 text-xs leading-relaxed space-y-2 mt-8">
          <div className="flex items-center gap-2 text-slate-800 font-bold uppercase tracking-wider text-[11px]">
            <AlertCircle className="w-4 h-4 text-slate-500" />
            <span>{disclaimerTitle}</span>
          </div>
          <p>
            <strong>AI Screening Notice:</strong> {disclaimerBody1}
          </p>
          <p>
            {disclaimerBody2}
          </p>
        </div>
      </div>
    </div>
  );
};
